### ISSUE TITLE
亞德克修改

### ISSUE THREAD

**Issue by dream3cmp3** [fdjkgh580/issue_artdeco#20]
1.	環景檔無法上傳(狀況如下圖)
請問該如何上傳環景檔呢? Rar or zip?
![image](https://cloud.githubusercontent.com/assets/10286429/5626413/e6753140-95c5-11e4-95a4-14183da46f51.png)

2.	首頁
首頁的圖示字要改小 但只有改了New Case,另外兩個沒改到
![image](https://cloud.githubusercontent.com/assets/10286429/5626416/f36c8f60-95c5-11e4-910c-e89314523d3c.png)
這邊我在修改唷！

3.	服務案例
a.	Logo banner歪掉了(!)
b.	相片集縮圖離代表圖太遠了
c.	服務案例跨類別顯示的功能(ex: 同時是 藝文展覽 也是 數位科技展 )
![image](https://cloud.githubusercontent.com/assets/10286429/5626419/100c63e8-95c6-11e4-88d7-9ef94dee30a6.png)

4.	展覽資訊
![image](https://cloud.githubusercontent.com/assets/10286429/5626423/1c68811c-95c6-11e4-92fc-805ab87bab78.png)
a.	連結部分請改為文字超連結
如:  連結：粉絲專頁
![image](https://cloud.githubusercontent.com/assets/10286429/5626426/25dcd9aa-95c6-11e4-98c5-c01f6217ebc7.png)
b.	展覽資訊內頁
發佈時間不須顯示
展覽標題置中
圖片與時地資訊欄切齊

**Comment by fdjkgh580** [comment]
@dream3cmp3 
 服務案例跨類別顯示的功能 > 如果改成跨類別的話，系統會大改喔

**Comment by fdjkgh580** [comment]
@dream3cmp3 
服務案例跨類別顯示的功能(ex: 同時是 藝文展覽 也是 數位科技展 )
這樣子系統結構會大改喔，等於是分類的方法要重新改掉喔。
