### ISSUE TITLE
環景上傳問題

### ISSUE THREAD

**Issue by Wondershow-Mars** [fdjkgh580/issue_artdeco#22]
為什麼亞德克過去做的三個環景(全何/資訊月主題館/賓士)
只有全何的環景我放得上去，其他兩個都錯誤(找不到)呢?我應該如何將另外兩個也上傳呢?
我有將兩個壓縮檔都上傳到環景管理裡了
要麻煩您幫我看看是什麼問題唷!

**Comment by fdjkgh580** [comment]
@Wondershow-Mars 
檔案要記得是 zip 公用格式喔。RAR是WinRAR廠商的格式，壓成zip後在上傳喔。
然後直接用檔案壓縮，裡面不要包一層資料夾喔。

---
## 例如不能這樣喔
![image](https://cloud.githubusercontent.com/assets/4414580/5716922/76c6c814-9b32-11e4-83d5-d422491f9432.png)

-----
## 應該要這樣
![image](https://cloud.githubusercontent.com/assets/4414580/5716931/abf8b0b0-9b32-11e4-83db-fcbbdda26f6b.png)
