### ISSUE TITLE
關於頁數問題

### ISSUE THREAD

**Issue by Wondershow-Mars** [fdjkgh580/issue_artdeco#29]
目前網站若超出8個沒有頁數可以顯示
![image](https://cloud.githubusercontent.com/assets/10335170/6100575/1b565c80-b04d-11e4-9ad9-543267fe080f.png)

**Comment by dream3cmp3** [comment]
![image](https://cloud.githubusercontent.com/assets/10286429/6365204/19e83942-bcee-11e4-8e1b-b78bb82c9179.png)

**Comment by fdjkgh580** [comment]
添加頁數了，超過6個會出現頁碼
