### ISSUE TITLE
手機版問題

### ISSUE THREAD

**Issue by Wondershow-Mars** [fdjkgh580/issue_artdeco#30]
首頁 字疊在圖示上，如下圖
我是用Sony跟iPhone、小米機看的，問題一樣～
請你檢查一下唷，謝謝！
![image](https://cloud.githubusercontent.com/assets/10335170/6100585/4196f3be-b04d-11e4-8931-c61f511d07b6.png)

**Comment by fdjkgh580** [comment]
OK，已解決
